sankey-beta

The source,Reading,100

Reading,The model,100

The model,Layered layout,45
The model,Chart layout,38
The model,Tree layout,17

Layered layout,The scene,45
Chart layout,The scene,38
Tree layout,The scene,17

The scene,The window,100
