// Write CHANGELOG.md from the git history.
//
// `task-1804` §6: *"201 commits and 34 minor versions with no record of what changed between them
// that a user could read. The commit history is greppable by ticket, which serves a developer and
// not a person deciding whether to update."*
//
// So the history is turned into that record, and it can be because of a convention the repository
// already keeps: **every commit that does something starts with its ticket**, `task-1804: …`. That
// prefix is what separates the work from the bookkeeping — the version bumps `tools/release.ps1`
// makes are `Unluminous <version>` and are not tickets, which is exactly what makes them the
// boundaries between one release and the next.
//
// ## Why a script rather than a file people edit
//
// A hand-written changelog is a file somebody forgets. This one is regenerated by `release.ps1` and
// `release.sh` on every release, from tags that are already there, so it cannot fall behind — the
// same argument `unluminous-cli/src/documentation.rs` makes about `commands.md` being a test.
//
// ## Node rather than PowerShell or bash
//
// Because there are two release scripts and one of them runs on a Mac with no `pwsh`. Node is what
// both platforms have here, and one reading of the history is better than two that have to agree.
//
// Usage:
//   node tools/changelog.mjs             writes CHANGELOG.md
//   node tools/changelog.mjs --check     exits 1 if the file on disk is not what would be written
//   node tools/changelog.mjs --stdout    prints it instead of writing it

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Run git in the repository and answer what it printed. */
function git(...args) {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8' }).trimEnd()
}

/**
 * Every `vN.N.N` tag, newest first, with the date it was made.
 *
 * By the tag's own date rather than by its name, because a version is released when it is released
 * and sorting names would put `v0.9.0` after `v0.34.2`.
 */
function releases() {
  const lines = git('for-each-ref', '--sort=-creatordate', '--format=%(refname:short)\t%(creatordate:short)', 'refs/tags/v*')
  if (!lines) return []
  return lines.split('\n').map(line => {
    const [tag, date] = line.split('\t')
    return { tag, date, version: tag.replace(/^v/, '') }
  })
}

/**
 * The ticket-prefixed subjects between two points in the history, oldest first.
 *
 * `from` is exclusive and may be undefined, which means the beginning of the history. Anything that
 * is not a ticket is dropped: a version bump, a merge, a typo fix nobody filed. That is the whole of
 * the filtering, and it is deliberate — a line a person can read is a line somebody wrote a ticket
 * for.
 */
function work(from, to) {
  const range = from ? `${from}..${to}` : to
  const lines = git('log', '--no-merges', '--reverse', '--pretty=%s', range)
  if (!lines) return []
  return lines
    .split('\n')
    .map(subject => subject.trim())
    .filter(subject => /^task-\d+:/.test(subject))
    .map(subject => {
      const [, ticket, said] = subject.match(/^(task-\d+):\s*(.*)$/)
      return { ticket, said: said.charAt(0).toUpperCase() + said.slice(1) }
    })
}

/** The whole document. */
function changelog() {
  const out = [
    '# Changelog',
    '',
    'What changed in each release of Unluminous, for somebody deciding whether to update.',
    '',
    'Written by `tools/changelog.mjs` from the git history, and rewritten by `tools/release.ps1` and',
    '`tools/release.sh` on every release, so it cannot fall behind. One line per ticket; the version',
    'bumps the release script makes are left out, because they are the boundaries rather than the work.',
    '',
  ]
  const tags = releases()
  const unreleased = work(tags[0]?.tag, 'HEAD')
  if (unreleased.length > 0) {
    out.push('## Unreleased', '')
    for (const entry of unreleased) out.push(`- ${entry.said} (\`${entry.ticket}\`)`)
    out.push('')
  }
  for (let index = 0; index < tags.length; index += 1) {
    const { tag, date, version } = tags[index]
    const entries = work(tags[index + 1]?.tag, tag)
    out.push(`## ${version} — ${date}`, '')
    if (entries.length === 0) {
      // Said rather than left blank: a release with nothing under it is a real thing -- a rebuild,
      // or a version bumped twice -- and an empty heading reads as a mistake.
      out.push('- No ticketed work; a rebuild of the version before it.', '')
      continue
    }
    for (const entry of entries) out.push(`- ${entry.said} (\`${entry.ticket}\`)`)
    out.push('')
  }
  return out.join('\n')
}

const wanted = changelog()
const path = join(repo, 'CHANGELOG.md')
if (process.argv.includes('--stdout')) {
  process.stdout.write(wanted)
} else if (process.argv.includes('--check')) {
  let have = ''
  try {
    have = readFileSync(path, 'utf8').replace(/\r\n/g, '\n')
  } catch {
    have = ''
  }
  if (have.trimEnd() !== wanted.trimEnd()) {
    console.error('CHANGELOG.md is not what the history says. Run: node tools/changelog.mjs')
    process.exit(1)
  }
  console.log('CHANGELOG.md is up to date.')
} else {
  writeFileSync(path, wanted, 'utf8')
  const releaseCount = releases().length
  console.log(`Wrote CHANGELOG.md: ${releaseCount} releases.`)
}
